goog.module('org.patternfly.component.tabs.OverflowTab');

goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLButtonElement.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLLIElement.$Overlay');
goog.require('java.lang.String');
goog.require('java.util.EnumSet');
goog.require('java.util.LinkedHashMap');
goog.require('java.util.List');
goog.require('java.util.Map');
goog.require('java.util.function.Consumer');
goog.require('java.util.function.Function');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Callback');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.Id');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.icon.InlineIcon');
goog.require('org.patternfly.component.menu.Menu');
goog.require('org.patternfly.component.menu.MenuContent');
goog.require('org.patternfly.component.menu.MenuItem');
goog.require('org.patternfly.component.menu.MenuItemType');
goog.require('org.patternfly.component.menu.MenuList');
goog.require('org.patternfly.component.tabs.Tab');
goog.require('org.patternfly.component.tabs.TabSubComponent');
goog.require('org.patternfly.component.tabs.Tabs');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Attributes');
goog.require('org.patternfly.core.Expandable');
goog.require('org.patternfly.core.SelectionMode');
goog.require('org.patternfly.handler.SelectHandler');
goog.require('org.patternfly.style.Classes');
goog.require('org.patternfly.style.Modifiers.Disabled');
goog.require('org.patternfly.style.PredefinedIcon');
goog.require('org.patternfly.thirdparty.popper.Modifiers');
goog.require('org.patternfly.thirdparty.popper.Placement');
goog.require('org.patternfly.thirdparty.popper.Popper');
goog.require('org.patternfly.thirdparty.popper.PopperBuilder');
goog.require('org.patternfly.thirdparty.popper.TriggerAction');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const OverflowTab = goog.require('org.patternfly.component.tabs.OverflowTab$impl');
exports = OverflowTab;
