goog.module('org.patternfly.showcase.component.CardComponent$impl');

const $Util = goog.require('nativebootstrap.Util$impl');
const ComponentPage = goog.require('org.patternfly.showcase.component.ComponentPage$impl');

let HTMLDivElement_$Overlay = goog.forwardDeclare('elemental2.dom.HTMLDivElement.$Overlay$impl');
let $Overlay = goog.forwardDeclare('elemental2.dom.HTMLParagraphElement.$Overlay$impl');
let j_l_String = goog.forwardDeclare('java.lang.String$impl');
let Supplier = goog.forwardDeclare('java.util.function.Supplier$impl');
let Elements = goog.forwardDeclare('org.jboss.elemento.Elements$impl');
let HTMLContainerBuilder = goog.forwardDeclare('org.jboss.elemento.HTMLContainerBuilder$impl');
let HTMLElementBuilder = goog.forwardDeclare('org.jboss.elemento.HTMLElementBuilder$impl');
let InputType = goog.forwardDeclare('org.jboss.elemento.InputType$impl');
let Card = goog.forwardDeclare('org.patternfly.component.Card$impl');
let Body = goog.forwardDeclare('org.patternfly.component.Card.Body$impl');
let Footer = goog.forwardDeclare('org.patternfly.component.Card.Footer$impl');
let Head = goog.forwardDeclare('org.patternfly.component.Card.Head$impl');
let Actions = goog.forwardDeclare('org.patternfly.component.Card.Head.Actions$impl');
let Header = goog.forwardDeclare('org.patternfly.component.Card.Header$impl');
let Dropdown = goog.forwardDeclare('org.patternfly.component.Dropdown$impl');
let Classes = goog.forwardDeclare('org.patternfly.layout.Classes$impl');
let Snippet = goog.forwardDeclare('org.patternfly.showcase.component.Snippet$impl');
let $Arrays = goog.forwardDeclare('vmbootstrap.Arrays$impl');
let $Casts = goog.forwardDeclare('vmbootstrap.Casts$impl');

/**
 * @deprecated
 */
class CardComponent extends ComponentPage {
 /** @protected @nodts */
 constructor() {
  super();
 }
 /** @nodts @return {!CardComponent} */
 static $create__() {
  CardComponent.$clinit();
  let $instance = new CardComponent();
  $instance.$ctor__org_patternfly_showcase_component_CardComponent__void();
  return $instance;
 }
 /** @nodts */
 $ctor__org_patternfly_showcase_component_CardComponent__void() {
  this.$ctor__org_patternfly_showcase_component_ComponentPage__java_lang_String__java_lang_String__java_lang_String__elemental2_dom_HTMLElement__void('Card', 'https://patternfly-java.github.io/patternfly-java/', 'https://www.patternfly.org/components/card/design-guidelines', /**@type {HTMLParagraphElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLParagraphElement>}*/ ($Casts.$to(Elements.m_p__org_jboss_elemento_HTMLContainerBuilder().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('A card is a flexible element for containing any kind of content. Cards are used on dashboards, in data displays (e.g. Card View), or for positioning content on a page.'), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), $Overlay)));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('simple-card', 'Simple card', 'Resources.get().cardSimple().getText()', Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(Card.m_card__org_patternfly_component_Card().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Header}*/ ($Casts.$to(Card.m_header__org_patternfly_component_Card_Header().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Header'), Header))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Body}*/ ($Casts.$to(Card.m_body__org_patternfly_component_Card_Body().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Body'), Body))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Footer}*/ ($Casts.$to(Card.m_footer__org_patternfly_component_Card_Footer().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Footer'), Footer))), Card))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('card-image', 'Card with an image and actions', 'Resources.get().cardImageActions().getText()', Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(Card.m_card__org_patternfly_component_Card().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Head}*/ ($Casts.$to(/**@type {Head}*/ ($Casts.$to(Card.m_head__org_patternfly_component_Card_Head().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {HTMLElementBuilder<HTMLImageElement>}*/ ($Casts.$to(Elements.m_img__java_lang_String__org_jboss_elemento_HTMLElementBuilder('./pf_logo.svg').m_style__java_lang_String__org_jboss_elemento_TypedBuilder('width: 300px'), HTMLElementBuilder))), Head)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Actions}*/ ($Casts.$to(/**@type {Actions}*/ ($Casts.$to(Head.m_actions__org_patternfly_component_Card_Head_Actions().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Dropdown<?string>}*/ (Dropdown.m_kebab__org_patternfly_component_Dropdown()).m_right__org_patternfly_component_Dropdown().m_add__java_lang_Object__org_patternfly_component_Dropdown('Link').m_add__java_lang_Object__org_patternfly_component_Dropdown('Action').m_addSeparator__org_patternfly_component_Dropdown().m_add__java_lang_Object__org_patternfly_component_Dropdown('Separated Link')), Actions)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Elements.m_input__org_jboss_elemento_InputType__org_jboss_elemento_InputElementBuilder(InputType.f_checkbox__org_jboss_elemento_InputType)), Actions))), Head))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Header}*/ ($Casts.$to(Card.m_header__org_patternfly_component_Card_Header().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Header'), Header))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Body}*/ ($Casts.$to(Card.m_body__org_patternfly_component_Card_Body().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Body'), Body))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Footer}*/ ($Casts.$to(Card.m_footer__org_patternfly_component_Card_Footer().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Footer'), Footer))), Card))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('card-header', 'Card header in card head', 'Resources.get().cardHeaderInHead().getText()', Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(Card.m_card__org_patternfly_component_Card().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Head}*/ ($Casts.$to(/**@type {Head}*/ ($Casts.$to(Card.m_head__org_patternfly_component_Card_Head().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Actions}*/ ($Casts.$to(/**@type {Actions}*/ ($Casts.$to(Head.m_actions__org_patternfly_component_Card_Head_Actions().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Dropdown<?string>}*/ (Dropdown.m_kebab__org_patternfly_component_Dropdown()).m_right__org_patternfly_component_Dropdown().m_add__java_lang_Object__org_patternfly_component_Dropdown('Link').m_add__java_lang_Object__org_patternfly_component_Dropdown('Action').m_addSeparator__org_patternfly_component_Dropdown().m_add__java_lang_Object__org_patternfly_component_Dropdown('Separated Link')), Actions)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Elements.m_input__org_jboss_elemento_InputType__org_jboss_elemento_InputElementBuilder(InputType.f_checkbox__org_jboss_elemento_InputType)), Actions))), Head)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Header}*/ ($Casts.$to(Card.m_header__org_patternfly_component_Card_Header().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('This is a really really really really really really really really really really long header'), Header))), Head))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Header}*/ ($Casts.$to(Card.m_header__org_patternfly_component_Card_Header().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Header'), Header))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Body}*/ ($Casts.$to(Card.m_body__org_patternfly_component_Card_Body().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Body'), Body))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Footer}*/ ($Casts.$to(Card.m_footer__org_patternfly_component_Card_Footer().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Footer'), Footer))), Card))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('card-actions', 'Only actions in card head (no header/footer)', 'Resources.get().cardActionsInHead().getText()', Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(Card.m_card__org_patternfly_component_Card().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Head}*/ ($Casts.$to(Card.m_head__org_patternfly_component_Card_Head().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Actions}*/ ($Casts.$to(/**@type {Actions}*/ ($Casts.$to(Head.m_actions__org_patternfly_component_Card_Head_Actions().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Dropdown<?string>}*/ (Dropdown.m_kebab__org_patternfly_component_Dropdown()).m_right__org_patternfly_component_Dropdown().m_add__java_lang_Object__org_patternfly_component_Dropdown('Link').m_add__java_lang_Object__org_patternfly_component_Dropdown('Action').m_addSeparator__org_patternfly_component_Dropdown().m_add__java_lang_Object__org_patternfly_component_Dropdown('Separated Link')), Actions)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Elements.m_input__org_jboss_elemento_InputType__org_jboss_elemento_InputElementBuilder(InputType.f_checkbox__org_jboss_elemento_InputType)), Actions))), Head))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Body}*/ ($Casts.$to(Card.m_body__org_patternfly_component_Card_Body().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('This is the card body, there are only actions in the card head.'), Body))), Card))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('card-image-only', 'Only image in the card head', 'Resources.get().cardImageInHead().getText()', Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(Card.m_card__org_patternfly_component_Card().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Head}*/ ($Casts.$to(Card.m_head__org_patternfly_component_Card_Head().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {HTMLElementBuilder<HTMLImageElement>}*/ ($Casts.$to(Elements.m_img__java_lang_String__org_jboss_elemento_HTMLElementBuilder('./pf_logo.svg').m_style__java_lang_String__org_jboss_elemento_TypedBuilder('width: 300px'), HTMLElementBuilder))), Head))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Header}*/ ($Casts.$to(Card.m_header__org_patternfly_component_Card_Header().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Header'), Header))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Body}*/ ($Casts.$to(Card.m_body__org_patternfly_component_Card_Body().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Body'), Body))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Footer}*/ ($Casts.$to(Card.m_footer__org_patternfly_component_Card_Footer().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Footer'), Footer))), Card))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('card-no-footer', 'Card with no footer', 'Resources.get().cardNoFooter().getText()', Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(Card.m_card__org_patternfly_component_Card().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Header}*/ ($Casts.$to(Card.m_header__org_patternfly_component_Card_Header().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Header'), Header))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Body}*/ ($Casts.$to(Card.m_body__org_patternfly_component_Card_Body().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('This card has no footer'), Body))), Card))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('card-no-header', 'Card with no header', 'Resources.get().cardNoHeader().getText()', Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(Card.m_card__org_patternfly_component_Card().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Body}*/ ($Casts.$to(Card.m_body__org_patternfly_component_Card_Body().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('This card has no header'), Body))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Footer}*/ ($Casts.$to(Card.m_footer__org_patternfly_component_Card_Footer().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Footer'), Footer))), Card))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('card-content', 'Card with only a content section', 'Resources.get().cardContentOnly().getText()', Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Card}*/ ($Casts.$to(Card.m_card__org_patternfly_component_Card().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Body}*/ ($Casts.$to(Card.m_body__org_patternfly_component_Card_Body().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Body'), Body))), Card))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('card-m-body', 'Card with multiple body sections', 'Resources.get().cardMultipleBodies().getText()', Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(Card.m_card__org_patternfly_component_Card().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Header}*/ ($Casts.$to(Card.m_header__org_patternfly_component_Card_Header().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Header'), Header))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Body}*/ ($Casts.$to(Card.m_body__org_patternfly_component_Card_Body().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Body'), Body))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Body}*/ ($Casts.$to(Card.m_body__org_patternfly_component_Card_Body().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Body'), Body))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Body}*/ ($Casts.$to(Card.m_body__org_patternfly_component_Card_Body().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Body'), Body))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Footer}*/ ($Casts.$to(Card.m_footer__org_patternfly_component_Card_Footer().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Footer'), Footer))), Card))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('card-body-fit', 'Card with only one body that fills', 'Resources.get().cardBodyFill().getText()', Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(Card.m_card__org_patternfly_component_Card().m_style__java_lang_String__org_jboss_elemento_TypedBuilder('min-height: 30em;'), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Header}*/ ($Casts.$to(Card.m_header__org_patternfly_component_Card_Header().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Header'), Header))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Body}*/ ($Casts.$to(/**@type {Body}*/ ($Casts.$to(Card.m_body__org_patternfly_component_Card_Body().m_css__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$init([Classes.m_modifier__java_lang_String__java_lang_String(Classes.f_noFill__org_patternfly_layout_Classes)], j_l_String))), Body)).m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Body pf-m-no-fill'), Body))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Body}*/ ($Casts.$to(/**@type {Body}*/ ($Casts.$to(Card.m_body__org_patternfly_component_Card_Body().m_css__arrayOf_java_lang_String__org_jboss_elemento_TypedBuilder(/**@type {!Array<?string>}*/ ($Arrays.$init([Classes.m_modifier__java_lang_String__java_lang_String(Classes.f_noFill__org_patternfly_layout_Classes)], j_l_String))), Body)).m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Body pf-m-no-fill'), Body))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Body}*/ ($Casts.$to(Card.m_body__org_patternfly_component_Card_Body().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Body'), Body))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Footer}*/ ($Casts.$to(Card.m_footer__org_patternfly_component_Card_Footer().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Footer'), Footer))), Card))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('card-hover', 'Card hover example', 'Resources.get().cardHover().getText()', Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(Card.m_card__org_patternfly_component_Card().m_hoverable__org_patternfly_component_Card().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Header}*/ ($Casts.$to(Card.m_header__org_patternfly_component_Card_Header().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Header'), Header))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Body}*/ ($Casts.$to(Card.m_body__org_patternfly_component_Card_Body().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Body'), Body))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Footer}*/ ($Casts.$to(Card.m_footer__org_patternfly_component_Card_Footer().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Footer'), Footer))), Card))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('card-compact', 'Card compact example', 'Resources.get().cardCompact().getText()', Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(/**@type {Card}*/ ($Casts.$to(Card.m_card__org_patternfly_component_Card().m_compact__org_patternfly_component_Card().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Header}*/ ($Casts.$to(Card.m_header__org_patternfly_component_Card_Header().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Header'), Header))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Body}*/ ($Casts.$to(Card.m_body__org_patternfly_component_Card_Body().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Body'), Body))), Card)).m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Footer}*/ ($Casts.$to(Card.m_footer__org_patternfly_component_Card_Footer().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('Footer'), Footer))), Card))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
 }
 /** @nodts */
 static $clinit() {
  CardComponent.$clinit = () =>{};
  CardComponent.$loadModules();
  ComponentPage.$clinit();
 }
 /** @nodts @return {boolean} */
 static $isInstance(/** ? */ instance) {
  return instance instanceof CardComponent;
 }
 
 /** @nodts */
 static $loadModules() {
  HTMLDivElement_$Overlay = goog.module.get('elemental2.dom.HTMLDivElement.$Overlay$impl');
  $Overlay = goog.module.get('elemental2.dom.HTMLParagraphElement.$Overlay$impl');
  j_l_String = goog.module.get('java.lang.String$impl');
  Supplier = goog.module.get('java.util.function.Supplier$impl');
  Elements = goog.module.get('org.jboss.elemento.Elements$impl');
  HTMLContainerBuilder = goog.module.get('org.jboss.elemento.HTMLContainerBuilder$impl');
  HTMLElementBuilder = goog.module.get('org.jboss.elemento.HTMLElementBuilder$impl');
  InputType = goog.module.get('org.jboss.elemento.InputType$impl');
  Card = goog.module.get('org.patternfly.component.Card$impl');
  Body = goog.module.get('org.patternfly.component.Card.Body$impl');
  Footer = goog.module.get('org.patternfly.component.Card.Footer$impl');
  Head = goog.module.get('org.patternfly.component.Card.Head$impl');
  Actions = goog.module.get('org.patternfly.component.Card.Head.Actions$impl');
  Header = goog.module.get('org.patternfly.component.Card.Header$impl');
  Dropdown = goog.module.get('org.patternfly.component.Dropdown$impl');
  Classes = goog.module.get('org.patternfly.layout.Classes$impl');
  Snippet = goog.module.get('org.patternfly.showcase.component.Snippet$impl');
  $Arrays = goog.module.get('vmbootstrap.Arrays$impl');
  $Casts = goog.module.get('vmbootstrap.Casts$impl');
 }
}
$Util.$setClassMetadata(CardComponent, 'org.patternfly.showcase.component.CardComponent');

exports = CardComponent;

//# sourceMappingURL=CardComponent.js.map
