goog.module('org.patternfly.showcase.component.DataListComponent');

goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLHeadingElement.$Overlay');
goog.require('elemental2.dom.HTMLLIElement.$Overlay');
goog.require('elemental2.dom.HTMLParagraphElement.$Overlay');
goog.require('java.lang.String');
goog.require('java.util.function.Function');
goog.require('java.util.function.Supplier');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.component.DataList');
goog.require('org.patternfly.component.DataList.Display');
goog.require('org.patternfly.component.DataList.ExpandableBody');
goog.require('org.patternfly.component.DataList.ExpandableContent');
goog.require('org.patternfly.component.DataList.ItemAction');
goog.require('org.patternfly.component.DataList.ItemCell');
goog.require('org.patternfly.component.DataList.ItemContent');
goog.require('org.patternfly.component.DataList.ItemRow');
goog.require('org.patternfly.component.Dropdown');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.dataprovider.DataProvider');
goog.require('org.patternfly.layout.Classes');
goog.require('org.patternfly.layout.PredefinedIcon');
goog.require('org.patternfly.showcase.LoremIpsum');
goog.require('org.patternfly.showcase.component.ComponentPage');
goog.require('org.patternfly.showcase.component.DataListComponent.DisplayData');
goog.require('org.patternfly.showcase.component.Snippet');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const DataListComponent = goog.require('org.patternfly.showcase.component.DataListComponent$impl');
exports = DataListComponent;
