goog.module('org.patternfly.showcase.component.MenuComponent$impl');

const $Util = goog.require('nativebootstrap.Util$impl');
const ComponentPage = goog.require('org.patternfly.showcase.component.ComponentPage$impl');

let HTMLDivElement_$Overlay = goog.forwardDeclare('elemental2.dom.HTMLDivElement.$Overlay$impl');
let $Overlay = goog.forwardDeclare('elemental2.dom.HTMLParagraphElement.$Overlay$impl');
let j_l_String = goog.forwardDeclare('java.lang.String$impl');
let List = goog.forwardDeclare('java.util.List$impl');
let j_u_function_Function = goog.forwardDeclare('java.util.function.Function$impl');
let Supplier = goog.forwardDeclare('java.util.function.Supplier$impl');
let Collectors = goog.forwardDeclare('java.util.stream.Collectors$impl');
let Stream = goog.forwardDeclare('java.util.stream.Stream$impl');
let Elements = goog.forwardDeclare('org.jboss.elemento.Elements$impl');
let HTMLContainerBuilder = goog.forwardDeclare('org.jboss.elemento.HTMLContainerBuilder$impl');
let Button = goog.forwardDeclare('org.patternfly.component.button.Button$impl');
let Menu = goog.forwardDeclare('org.patternfly.component.menu.Menu$impl');
let MenuActionHandler = goog.forwardDeclare('org.patternfly.component.menu.MenuActionHandler$impl');
let MenuContent = goog.forwardDeclare('org.patternfly.component.menu.MenuContent$impl');
let MenuFooter = goog.forwardDeclare('org.patternfly.component.menu.MenuFooter$impl');
let MenuGroup = goog.forwardDeclare('org.patternfly.component.menu.MenuGroup$impl');
let MenuItem = goog.forwardDeclare('org.patternfly.component.menu.MenuItem$impl');
let MenuItemAction = goog.forwardDeclare('org.patternfly.component.menu.MenuItemAction$impl');
let MenuList = goog.forwardDeclare('org.patternfly.component.menu.MenuList$impl');
let Aria = goog.forwardDeclare('org.patternfly.core.Aria$impl');
let SelectionMode = goog.forwardDeclare('org.patternfly.core.SelectionMode$impl');
let ComponentHandler = goog.forwardDeclare('org.patternfly.handler.ComponentHandler$impl');
let MultiSelectHandler = goog.forwardDeclare('org.patternfly.handler.MultiSelectHandler$impl');
let SelectHandler = goog.forwardDeclare('org.patternfly.handler.SelectHandler$impl');
let PredefinedIcon = goog.forwardDeclare('org.patternfly.layout.PredefinedIcon$impl');
let LoremIpsum = goog.forwardDeclare('org.patternfly.showcase.LoremIpsum$impl');
let Snippet = goog.forwardDeclare('org.patternfly.showcase.component.Snippet$impl');
let $Casts = goog.forwardDeclare('vmbootstrap.Casts$impl');

class MenuComponent extends ComponentPage {
 /** @protected @nodts */
 constructor() {
  super();
 }
 /** @nodts @return {!MenuComponent} */
 static $create__() {
  MenuComponent.$clinit();
  let $instance = new MenuComponent();
  $instance.$ctor__org_patternfly_showcase_component_MenuComponent__void();
  return $instance;
 }
 /** @nodts */
 $ctor__org_patternfly_showcase_component_MenuComponent__void() {
  this.$ctor__org_patternfly_showcase_component_ComponentPage__java_lang_String__java_lang_String__java_lang_String__elemental2_dom_HTMLElement__void('Menu', 'https://patternfly-java.github.io/patternfly-java/org/patternfly/component/menu/Menu.html', 'https://www.patternfly.org/components/menus/menu/design-guidelines', /**@type {HTMLParagraphElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLParagraphElement>}*/ ($Casts.$to(Elements.m_p__org_jboss_elemento_HTMLContainerBuilder().m_textContent__java_lang_String__org_jboss_elemento_TypedBuilder('A menu is a list of options or actions that users can choose from. It can be used in a variety of contexts whenever the user needs to choose between multiple values, options, or actions. A menu is most often paired with a menu toggle as its trigger, but can also be used inline or can be attached to other interactable elements to toggle it open and close.'), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), $Overlay)));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-basic', 'Basic menu', /**@type {?string}*/ ($Casts.$to(PatternFlyCode.code.get('menu-basic'), j_l_String)), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_core_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_core_SelectionMode).m_onSingleSelect__org_patternfly_handler_SelectHandler__org_patternfly_component_menu_Menu(SelectHandler.$adapt((item, /** boolean */ selected) =>{
    let item_1 = /**@type {MenuItem}*/ ($Casts.$to(item, MenuItem));
    goog.global.console.log('Item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(item_1.f_id__org_patternfly_component_menu_MenuItem) + ' selected');
   })).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuContent(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Action').m_onClick__org_patternfly_handler_ComponentHandler__org_patternfly_component_menu_MenuItem(ComponentHandler.$adapt((/** Event */ e, actionItem) =>{
    let actionItem_1 = /**@type {MenuItem}*/ ($Casts.$to(actionItem, MenuItem));
    goog.global.console.log('Clicked on action item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(actionItem_1.f_id__org_patternfly_component_menu_MenuItem));
   }))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Link', '#home').m_onClick__org_patternfly_handler_ComponentHandler__org_patternfly_component_menu_MenuItem(ComponentHandler.$adapt((/** Event */ e_1, item_2) =>{
    let item_3 = /**@type {MenuItem}*/ ($Casts.$to(item_2, MenuItem));
    e_1.preventDefault();
   }))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Disabled action').m_disabled__org_jboss_elemento_TypedBuilder(), MenuItem))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-3', 'Disabled link', '#').m_disabled__org_jboss_elemento_TypedBuilder(), MenuItem)))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-danger', 'Danger menu item', /**@type {?string}*/ ($Casts.$to(PatternFlyCode.code.get('menu-danger'), j_l_String)), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_core_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_core_SelectionMode).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuContent(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Action 1')).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Action 2')).m_addDivider__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Delete').m_danger__org_patternfly_component_menu_MenuItem())))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-icons', 'With icons', /**@type {?string}*/ ($Casts.$to(PatternFlyCode.code.get('menu-icons'), j_l_String)), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_core_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_core_SelectionMode).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuContent(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Item 1').m_icon__java_lang_String__org_patternfly_component_menu_MenuItem(PredefinedIcon.m_fas__java_lang_String__java_lang_String('code-branch'))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Container image').m_icon__java_lang_String__org_patternfly_component_menu_MenuItem(PredefinedIcon.m_fas__java_lang_String__java_lang_String('layer-group'))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'From Dockerfile').m_icon__java_lang_String__org_patternfly_component_menu_MenuItem(PredefinedIcon.m_fas__java_lang_String__java_lang_String('cube')))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-actions', 'With action', /**@type {?string}*/ ($Casts.$to(PatternFlyCode.code.get('menu-actions'), j_l_String)), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_core_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_multi__org_patternfly_core_SelectionMode).m_onAction__org_patternfly_component_menu_MenuActionHandler__org_patternfly_component_menu_Menu(MenuActionHandler.$adapt((/** MenuItemAction */ itemAction) =>{
    goog.global.console.log('Action ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(itemAction.f_id__org_patternfly_component_menu_MenuItemAction) + ' on item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(itemAction.f_menuItem__org_patternfly_component_menu_MenuItemAction.f_id__org_patternfly_component_menu_MenuItem) + ' clicked');
   })).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addGroup__org_patternfly_component_menu_MenuGroup__org_patternfly_component_menu_MenuContent(MenuGroup.m_menuGroup__java_lang_String__org_patternfly_component_menu_MenuGroup('Actions').m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuGroup(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Item 1').m_description__java_lang_String__org_patternfly_component_menu_MenuItem('This is a description').m_addAction__org_patternfly_component_menu_MenuItemAction__org_patternfly_component_menu_MenuItem(/**@type {MenuItemAction}*/ ($Casts.$to(MenuItemAction.m_menuItemAction__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItemAction('action-0', PredefinedIcon.m_fas__java_lang_String__java_lang_String('code-branch')).m_aria__java_lang_String__java_lang_String__org_jboss_elemento_TypedBuilder(Aria.f_label__org_patternfly_core_Aria, 'Code'), MenuItemAction)).m_onClick__org_patternfly_handler_ComponentHandler__org_patternfly_component_menu_MenuItemAction(ComponentHandler.$adapt((/** Event */ e_2, itemAction_1) =>{
    let itemAction_2 = /**@type {MenuItemAction}*/ ($Casts.$to(itemAction_1, MenuItemAction));
    goog.global.console.log('Code action clicked');
   })))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Item 2').m_description__java_lang_String__org_patternfly_component_menu_MenuItem('This is a description').m_disabled__org_jboss_elemento_TypedBuilder(), MenuItem)).m_addAction__org_patternfly_component_menu_MenuItemAction__org_patternfly_component_menu_MenuItem(MenuItemAction.m_menuItemAction__java_lang_String__org_patternfly_layout_PredefinedIcon__org_patternfly_component_menu_MenuItemAction('action-1', PredefinedIcon.f_bell__org_patternfly_layout_PredefinedIcon))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Item 3').m_addAction__org_patternfly_component_menu_MenuItemAction__org_patternfly_component_menu_MenuItem(MenuItemAction.m_menuItemAction__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItemAction('action-2', PredefinedIcon.m_fas__java_lang_String__java_lang_String('clipboard')))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-3', 'Item 4').m_description__java_lang_String__org_patternfly_component_menu_MenuItem('This is a description').m_addAction__org_patternfly_component_menu_MenuItemAction__org_patternfly_component_menu_MenuItem(MenuItemAction.m_menuItemAction__java_lang_String__org_patternfly_layout_PredefinedIcon__org_patternfly_component_menu_MenuItemAction('action-3', PredefinedIcon.f_bars__org_patternfly_layout_PredefinedIcon))))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-links', 'With links', /**@type {?string}*/ ($Casts.$to(PatternFlyCode.code.get('menu-links'), j_l_String)), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_core_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_core_SelectionMode).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuContent(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Link 1', '#home').m_external__org_patternfly_component_menu_MenuItem()).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Link 2', '#home').m_external__org_patternfly_component_menu_MenuItem()).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Link 3', '#home'))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-descriptions', 'With descriptions', /**@type {?string}*/ ($Casts.$to(PatternFlyCode.code.get('menu-descriptions'), j_l_String)), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_core_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_core_SelectionMode).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuContent(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Action 1').m_icon__java_lang_String__org_patternfly_component_menu_MenuItem(PredefinedIcon.m_fas__java_lang_String__java_lang_String('code-branch')).m_description__java_lang_String__org_patternfly_component_menu_MenuItem('Description')).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Action 2 disabled').m_icon__java_lang_String__org_patternfly_component_menu_MenuItem(PredefinedIcon.m_fas__java_lang_String__java_lang_String('code-branch')).m_description__java_lang_String__org_patternfly_component_menu_MenuItem('Description').m_disabled__org_jboss_elemento_TypedBuilder(), MenuItem))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Action 3').m_icon__java_lang_String__org_patternfly_component_menu_MenuItem(PredefinedIcon.m_fas__java_lang_String__java_lang_String('code-branch')).m_description__java_lang_String__org_patternfly_component_menu_MenuItem(LoremIpsum.m_words__int__java_lang_String(50)))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-checkbox', 'Item checkbox', /**@type {?string}*/ ($Casts.$to(PatternFlyCode.code.get('menu-checkbox'), j_l_String)), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_core_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_multi__org_patternfly_core_SelectionMode).m_onMultiSelect__org_patternfly_handler_MultiSelectHandler__org_patternfly_component_menu_Menu(MultiSelectHandler.$adapt((/** List<MenuItem> */ menuItems) =>{
    goog.global.console.log('### Selected items: ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(/**@type {?string}*/ ($Casts.$to(/**@type {Stream<?string>}*/ (menuItems.m_stream__java_util_stream_Stream().m_map__java_util_function_Function__java_util_stream_Stream(j_u_function_Function.$adapt((mi) =>{
     let mi_1 = /**@type {MenuItem}*/ ($Casts.$to(mi, MenuItem));
     return mi_1.f_id__org_patternfly_component_menu_MenuItem;
    }))).m_collect__java_util_stream_Collector__java_lang_Object(Collectors.m_joining__java_lang_CharSequence__java_util_stream_Collector(', ')), j_l_String))));
   })).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuContent(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_checkboxMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Checkbox 1').m_onClick__org_patternfly_handler_ComponentHandler__org_patternfly_component_menu_MenuItem(ComponentHandler.$adapt((/** Event */ e_3, mi_2) =>{
    let mi_3 = /**@type {MenuItem}*/ ($Casts.$to(mi_2, MenuItem));
    goog.global.console.log('+++ Clicked on item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(mi_3.f_id__org_patternfly_component_menu_MenuItem));
   }))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_checkboxMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Checkbox 2').m_onClick__org_patternfly_handler_ComponentHandler__org_patternfly_component_menu_MenuItem(ComponentHandler.$adapt((/** Event */ e_4, mi_4) =>{
    let mi_5 = /**@type {MenuItem}*/ ($Casts.$to(mi_4, MenuItem));
    goog.global.console.log('+++ Clicked on item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(mi_5.f_id__org_patternfly_component_menu_MenuItem));
   }))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_checkboxMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Checkbox 3').m_onClick__org_patternfly_handler_ComponentHandler__org_patternfly_component_menu_MenuItem(ComponentHandler.$adapt((/** Event */ e_5, mi_6) =>{
    let mi_7 = /**@type {MenuItem}*/ ($Casts.$to(mi_6, MenuItem));
    goog.global.console.log('+++ Clicked on item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(mi_7.f_id__org_patternfly_component_menu_MenuItem));
   })).m_disabled__org_jboss_elemento_TypedBuilder(), MenuItem)))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-footer', 'Menu footer', /**@type {?string}*/ ($Casts.$to(PatternFlyCode.code.get('menu-footer'), j_l_String)), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_core_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_core_SelectionMode).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuContent(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Action')).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Link', '#home')).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Disabled action').m_disabled__org_jboss_elemento_TypedBuilder(), MenuItem))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(/**@type {MenuItem}*/ ($Casts.$to(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-3', 'Disabled link', '#').m_disabled__org_jboss_elemento_TypedBuilder(), MenuItem))))).m_addFooter__org_patternfly_component_menu_MenuFooter__org_patternfly_component_menu_Menu(/**@type {MenuFooter}*/ ($Casts.$to(MenuFooter.m_menuFooter__org_patternfly_component_menu_MenuFooter().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(/**@type {Button}*/ ($Casts.$to(Button.m_button__java_lang_String__org_patternfly_component_button_Button('Action').m_link__org_patternfly_component_button_Button().m_inline__org_jboss_elemento_TypedBuilder(), Button))), MenuFooter)))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-separator', 'Separated items', /**@type {?string}*/ ($Casts.$to(PatternFlyCode.code.get('menu-separator'), j_l_String)), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_core_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_core_SelectionMode).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuContent(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Action 1')).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Action 2')).m_addDivider__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Action 3'))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-titled-groups', 'Titled groups of items', /**@type {?string}*/ ($Casts.$to(PatternFlyCode.code.get('menu-titled-groups'), j_l_String)), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_core_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_core_SelectionMode).m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addGroup__org_patternfly_component_menu_MenuGroup__org_patternfly_component_menu_MenuContent(MenuGroup.m_menuGroup__org_patternfly_component_menu_MenuGroup().m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuGroup(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Link not in group', '#')))).m_addDivider__org_patternfly_component_menu_MenuContent().m_addGroup__org_patternfly_component_menu_MenuGroup__org_patternfly_component_menu_MenuContent(MenuGroup.m_menuGroup__java_lang_String__org_patternfly_component_menu_MenuGroup('Group 1').m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuGroup(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_add__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-10', 'Link 1', '#')).m_add__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-11', 'Link 2', '#')))).m_addDivider__org_patternfly_component_menu_MenuContent().m_addGroup__org_patternfly_component_menu_MenuGroup__org_patternfly_component_menu_MenuContent(MenuGroup.m_menuGroup__java_lang_String__org_patternfly_component_menu_MenuGroup('Group 2').m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuGroup(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_add__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-20', 'Link 1', '#')).m_add__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_linkMenuItem__java_lang_String__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-21', 'Link 2', '#')))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
  this.m_addSnippet__org_patternfly_showcase_component_Snippet__void_$pp_org_patternfly_showcase_component(Snippet.$create__java_lang_String__java_lang_String__java_lang_String__java_util_function_Supplier('menu-favorites', 'With favorites', /**@type {?string}*/ ($Casts.$to(PatternFlyCode.code.get('menu-favorites'), j_l_String)), Supplier.$adapt(() =>{
   return /**@type {HTMLDivElement}*/ ($Casts.$to(/**@type {HTMLContainerBuilder<HTMLDivElement>}*/ ($Casts.$to(Elements.m_div__org_jboss_elemento_HTMLContainerBuilder().m_add__org_jboss_elemento_IsElement__org_jboss_elemento_TypedBuilder(Menu.m_menu__org_patternfly_core_SelectionMode__org_patternfly_component_menu_Menu(SelectionMode.f_click__org_patternfly_core_SelectionMode).m_onSingleSelect__org_patternfly_handler_SelectHandler__org_patternfly_component_menu_Menu(SelectHandler.$adapt((item_4, /** boolean */ selected_1) =>{
    let item_5 = /**@type {MenuItem}*/ ($Casts.$to(item_4, MenuItem));
    goog.global.console.log('Item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(item_5.f_id__org_patternfly_component_menu_MenuItem) + ' selected');
   })).m_onAction__org_patternfly_component_menu_MenuActionHandler__org_patternfly_component_menu_Menu(MenuActionHandler.$adapt((/** MenuItemAction */ itemAction_3) =>{
    goog.global.console.log('Action ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(itemAction_3.f_id__org_patternfly_component_menu_MenuItemAction) + ' on item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(itemAction_3.f_menuItem__org_patternfly_component_menu_MenuItemAction.f_id__org_patternfly_component_menu_MenuItem) + ' clicked');
   })).m_favorites__org_patternfly_component_menu_Menu().m_addContent__org_patternfly_component_menu_MenuContent__org_patternfly_component_menu_Menu(MenuContent.m_menuContent__org_patternfly_component_menu_MenuContent().m_addGroup__org_patternfly_component_menu_MenuGroup__org_patternfly_component_menu_MenuContent(MenuGroup.m_menuGroup__java_lang_String__org_patternfly_component_menu_MenuGroup('All actions').m_addList__org_patternfly_component_menu_MenuList__org_patternfly_component_menu_MenuGroup(MenuList.m_menuList__org_patternfly_component_menu_MenuList().m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-0', 'Item 1').m_description__java_lang_String__org_patternfly_component_menu_MenuItem('Description 1').m_addAction__org_patternfly_component_menu_MenuItemAction__org_patternfly_component_menu_MenuItem(MenuItemAction.m_menuItemAction__java_lang_String__org_patternfly_layout_PredefinedIcon__org_patternfly_component_menu_MenuItemAction('action-0', PredefinedIcon.f_bars__org_patternfly_layout_PredefinedIcon))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-1', 'Item 2').m_onClick__org_patternfly_handler_ComponentHandler__org_patternfly_component_menu_MenuItem(ComponentHandler.$adapt((/** Event */ e_6, item_6) =>{
    let item_7 = /**@type {MenuItem}*/ ($Casts.$to(item_6, MenuItem));
    goog.global.console.log('# Item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(item_7.f_id__org_patternfly_component_menu_MenuItem) + ' clicked');
   })).m_description__java_lang_String__org_patternfly_component_menu_MenuItem('Description 2').m_addAction__org_patternfly_component_menu_MenuItemAction__org_patternfly_component_menu_MenuItem(MenuItemAction.m_menuItemAction__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItemAction('action-1', PredefinedIcon.m_fas__java_lang_String__java_lang_String('clipboard')).m_onClick__org_patternfly_handler_ComponentHandler__org_patternfly_component_menu_MenuItemAction(ComponentHandler.$adapt((/** Event */ e_7, itemAction_4) =>{
    let itemAction_5 = /**@type {MenuItemAction}*/ ($Casts.$to(itemAction_4, MenuItemAction));
    goog.global.console.log('# Action ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(itemAction_5.f_id__org_patternfly_component_menu_MenuItemAction) + ' on item ' + j_l_String.m_valueOf__java_lang_Object__java_lang_String(itemAction_5.f_menuItem__org_patternfly_component_menu_MenuItemAction.f_id__org_patternfly_component_menu_MenuItem) + ' clicked');
   })))).m_addItem__org_patternfly_component_menu_MenuItem__org_patternfly_component_menu_MenuList(MenuItem.m_actionMenuItem__java_lang_String__java_lang_String__org_patternfly_component_menu_MenuItem('item-2', 'Item 3').m_description__java_lang_String__org_patternfly_component_menu_MenuItem('Description 3').m_addAction__org_patternfly_component_menu_MenuItemAction__org_patternfly_component_menu_MenuItem(MenuItemAction.m_menuItemAction__java_lang_String__org_patternfly_layout_PredefinedIcon__org_patternfly_component_menu_MenuItemAction('action-2', PredefinedIcon.f_bell__org_patternfly_layout_PredefinedIcon))))))), HTMLContainerBuilder)).m_element__elemental2_dom_HTMLElement(), HTMLDivElement_$Overlay));
  })));
 }
 /** @nodts */
 static $clinit() {
  MenuComponent.$clinit = () =>{};
  MenuComponent.$loadModules();
  ComponentPage.$clinit();
 }
 /** @nodts @return {boolean} */
 static $isInstance(/** ? */ instance) {
  return instance instanceof MenuComponent;
 }
 
 /** @nodts */
 static $loadModules() {
  HTMLDivElement_$Overlay = goog.module.get('elemental2.dom.HTMLDivElement.$Overlay$impl');
  $Overlay = goog.module.get('elemental2.dom.HTMLParagraphElement.$Overlay$impl');
  j_l_String = goog.module.get('java.lang.String$impl');
  j_u_function_Function = goog.module.get('java.util.function.Function$impl');
  Supplier = goog.module.get('java.util.function.Supplier$impl');
  Collectors = goog.module.get('java.util.stream.Collectors$impl');
  Elements = goog.module.get('org.jboss.elemento.Elements$impl');
  HTMLContainerBuilder = goog.module.get('org.jboss.elemento.HTMLContainerBuilder$impl');
  Button = goog.module.get('org.patternfly.component.button.Button$impl');
  Menu = goog.module.get('org.patternfly.component.menu.Menu$impl');
  MenuActionHandler = goog.module.get('org.patternfly.component.menu.MenuActionHandler$impl');
  MenuContent = goog.module.get('org.patternfly.component.menu.MenuContent$impl');
  MenuFooter = goog.module.get('org.patternfly.component.menu.MenuFooter$impl');
  MenuGroup = goog.module.get('org.patternfly.component.menu.MenuGroup$impl');
  MenuItem = goog.module.get('org.patternfly.component.menu.MenuItem$impl');
  MenuItemAction = goog.module.get('org.patternfly.component.menu.MenuItemAction$impl');
  MenuList = goog.module.get('org.patternfly.component.menu.MenuList$impl');
  Aria = goog.module.get('org.patternfly.core.Aria$impl');
  SelectionMode = goog.module.get('org.patternfly.core.SelectionMode$impl');
  ComponentHandler = goog.module.get('org.patternfly.handler.ComponentHandler$impl');
  MultiSelectHandler = goog.module.get('org.patternfly.handler.MultiSelectHandler$impl');
  SelectHandler = goog.module.get('org.patternfly.handler.SelectHandler$impl');
  PredefinedIcon = goog.module.get('org.patternfly.layout.PredefinedIcon$impl');
  LoremIpsum = goog.module.get('org.patternfly.showcase.LoremIpsum$impl');
  Snippet = goog.module.get('org.patternfly.showcase.component.Snippet$impl');
  $Casts = goog.module.get('vmbootstrap.Casts$impl');
 }
}
$Util.$setClassMetadata(MenuComponent, 'org.patternfly.showcase.component.MenuComponent');

exports = MenuComponent;

//# sourceMappingURL=MenuComponent.js.map
