goog.module('org.patternfly.showcase.component.Snippet');

goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLAnchorElement.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('java.lang.Object');
goog.require('java.lang.String');
goog.require('java.util.function.Supplier');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.By');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.Id');
goog.require('org.jboss.elemento.IsElement');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.component.code.CodeEditor');
goog.require('org.patternfly.component.code.CodeEditorAction');
goog.require('org.patternfly.component.code.CodeEditorActions');
goog.require('org.patternfly.component.code.CodeEditorHeader');
goog.require('org.patternfly.component.title.Title');
goog.require('org.patternfly.component.tooltip.Tooltip');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.Attributes');
goog.require('org.patternfly.handler.CloseHandler');
goog.require('org.patternfly.handler.ComponentHandler');
goog.require('org.patternfly.layout.Classes');
goog.require('org.patternfly.layout.PredefinedIcon');
goog.require('org.patternfly.layout.Size');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const Snippet = goog.require('org.patternfly.showcase.component.Snippet$impl');
exports = Snippet;
