goog.module('org.patternfly.component.card.CardHeader');

goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.MouseEvent.$Overlay');
goog.require('elemental2.dom.Node.$Overlay');
goog.require('java.lang.Iterable');
goog.require('java.lang.String');
goog.require('java.util.function.Consumer');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Container');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.Id');
goog.require('org.jboss.elemento.IsElement');
goog.require('org.patternfly.component.ComponentReference');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.SubComponent');
goog.require('org.patternfly.component.button.Button');
goog.require('org.patternfly.component.card.Card');
goog.require('org.patternfly.component.card.CardActions');
goog.require('org.patternfly.component.card.CardTitle');
goog.require('org.patternfly.component.icon.InlineIcon');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.layout.Classes');
goog.require('org.patternfly.layout.PredefinedIcon');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const CardHeader = goog.require('org.patternfly.component.card.CardHeader$impl');
exports = CardHeader;
