goog.module('org.patternfly.component.form.TextInput');

goog.require('elemental2.dom.Element.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.EventListener.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLInputElement.$Overlay');
goog.require('java.lang.String');
goog.require('java.util.function.Consumer');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.EventType');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.jboss.elemento.InputElementBuilder');
goog.require('org.jboss.elemento.InputType');
goog.require('org.patternfly.component.BaseComponent');
goog.require('org.patternfly.component.ComponentType');
goog.require('org.patternfly.component.icon.InlineIcon');
goog.require('org.patternfly.core.Aria');
goog.require('org.patternfly.core.HasValue');
goog.require('org.patternfly.core.Modifiers.Disabled');
goog.require('org.patternfly.core.Modifiers.Invalid');
goog.require('org.patternfly.core.Modifiers.Plain');
goog.require('org.patternfly.core.Modifiers.Readonly');
goog.require('org.patternfly.core.Modifiers.Required');
goog.require('org.patternfly.handler.ChangeHandler');
goog.require('org.patternfly.layout.Classes');
goog.require('org.patternfly.layout.PredefinedIcon');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const TextInput = goog.require('org.patternfly.component.form.TextInput$impl');
exports = TextInput;
