goog.module('org.patternfly.showcase.demo.server.ServerDemo');

goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLParagraphElement.$Overlay');
goog.require('elemental2.dom.HTMLTableCellElement.$Overlay');
goog.require('java.lang.Integer');
goog.require('java.lang.Iterable');
goog.require('java.lang.Object');
goog.require('java.lang.String');
goog.require('java.util.Arrays');
goog.require('java.util.Comparator');
goog.require('java.util.Iterator');
goog.require('java.util.List');
goog.require('java.util.Spliterator');
goog.require('java.util.function.Consumer');
goog.require('java.util.function.Function');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.component.DataTable');
goog.require('org.patternfly.component.DataTable.BodyDisplay');
goog.require('org.patternfly.component.DataTable.Column');
goog.require('org.patternfly.component.page.PageMainSection');
goog.require('org.patternfly.component.text.TextContent');
goog.require('org.patternfly.component.title.Title');
goog.require('org.patternfly.dataprovider.DataProvider');
goog.require('org.patternfly.layout.Size');
goog.require('org.patternfly.showcase.Page');
goog.require('org.patternfly.showcase.demo.server.Server.$Overlay');
goog.require('vmbootstrap.Casts');

const ServerDemo = goog.require('org.patternfly.showcase.demo.server.ServerDemo$impl');
exports = ServerDemo;
