goog.module('org.patternfly.showcase.layout.FlexLayout');

goog.require('elemental2.dom.HTMLDivElement.$Overlay');
goog.require('elemental2.dom.HTMLParagraphElement.$Overlay');
goog.require('java.lang.String');
goog.require('java.util.function.Supplier');
goog.require('nativebootstrap.Util');
goog.require('org.jboss.elemento.Elements');
goog.require('org.jboss.elemento.HTMLContainerBuilder');
goog.require('org.patternfly.layout.flex.Align');
goog.require('org.patternfly.layout.flex.AlignSelf');
goog.require('org.patternfly.layout.flex.Direction');
goog.require('org.patternfly.layout.flex.Display');
goog.require('org.patternfly.layout.flex.Flex');
goog.require('org.patternfly.layout.flex.FlexItem');
goog.require('org.patternfly.layout.flex.FlexShorthand');
goog.require('org.patternfly.layout.flex.Gap');
goog.require('org.patternfly.layout.flex.JustifyContent');
goog.require('org.patternfly.layout.flex.SpaceItems');
goog.require('org.patternfly.layout.flex.Spacer');
goog.require('org.patternfly.showcase.LoremIpsum');
goog.require('org.patternfly.showcase.Snippet');
goog.require('org.patternfly.showcase.SnippetPage');
goog.require('org.patternfly.style.Breakpoint');
goog.require('org.patternfly.style.Breakpoints');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');

const FlexLayout = goog.require('org.patternfly.showcase.layout.FlexLayout$impl');
exports = FlexLayout;
