stack().gutter()
        .addItem(stackItem()
                .add(expandableSection("detached-content")
                        .detachedFrom("detached-toggle")
                        .addContent(expandableSectionContent()
                                .textContent("This content is visible only when the component is expanded."))))
        .addItem(stackItem()
                .add(expandableSection("detached-toggle")
                        .detachedFrom("detached-content")
                        .addToggle(expandableSectionToggle("Show more", "Show less").up())));