textContent()
        .add(h(1)
                .add("Heading ")
                .add(icon(plusCircle).inline()))
        .add(p().textContent(LoremIpsum.paragraph()))
        .add(h(2)
                .add("Second level ")
                .add(icon(plusCircle).inline()))
        .add(p()
                .add(icon(plusCircle).inline())
                .add(" " + LoremIpsum.paragraphs(2) + " ")
                .add(strong()
                        .add(LoremIpsum.words(2) + " ")
                        .add(icon(plusCircle).inline()))
                .add(" " + LoremIpsum.words(5))
                .add(LoremIpsum.paragraphs(2)))
        .add(small()
                .add("Sometimes you need small text ")
                .add(icon(plusCircle).inline()))
        .add(div()
                .add("Inline with size specified: ")
                .add(icon(plusCircle).size(sm).inline())
                .add(" small, ")
                .add(icon(plusCircle).size(md).inline())
                .add(" medium, ")
                .add(icon(plusCircle).size(lg).inline())
                .add(" large, ")
                .add(icon(plusCircle).size(xl).inline())
                .add(" extra large"));