menu(click)
        .addContent(menuContent()
                .addList(menuList()
                        .addItem(actionMenuItem("item-0", "Action"))
                        .addItem(linkMenuItem("item-1", "Link", "#home"))
                        .addItem(actionMenuItem("item-2", "Disabled action")
                                .disabled())
                        .addItem(linkMenuItem("item-3", "Disabled link", "#")
                                .disabled())))
        .addFooter(menuFooter()
                .add(button("Action").link().inline()));