menu(multi)
        .onAction(itemAction -> console.log(
                "Action " + itemAction.id + " on item " + itemAction.menuItem.id + " clicked"))
        .addContent(menuContent()
                .addGroup(menuGroup("Actions")
                        .addList(menuList()
                                .addItem(actionMenuItem("item-0", "Item 1")
                                        .description("This is a description")
                                        .addAction(menuItemAction("action-0", fas("code-branch"))
                                                .aria(Aria.label, "Code")
                                                .onAction((e, itemAction) -> console.log(
                                                        "Code action clicked"))))
                                .addItem(actionMenuItem("item-1", "Item 2")
                                        .description("This is a description")
                                        .disabled()
                                        .addAction(menuItemAction("action-1", bell)))
                                .addItem(actionMenuItem("item-2", "Item 3")
                                        .addAction(menuItemAction("action-2", fas("clipboard"))))
                                .addItem(actionMenuItem("item-3", "Item 4")
                                        .description("This is a description")
                                        .addAction(menuItemAction("action-3", bars))))));