textContent()
        .add(h(1)
                .add("Heading ")
                .add(spinner("Spinner in heading").inline()))
        .add(p().textContent(LoremIpsum.paragraphs(1)))
        .add(h(2)
                .add("Second level ")
                .add(spinner("Spinner in subheading").inline()))
        .add(p()
                .add(LoremIpsum.paragraphs(2) + " ")
                .add(spinner("Spinner in paragraph").inline())
                .add(" " + LoremIpsum.paragraphs(3)))
        .add(small()
                .add("Sometimes you need small text ")
                .add(spinner("Spinner in small element").inline()));